apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: senzing-persistent-volume-claim
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: oketi-gluster
  volumeMode: Filesystem
