image:
  registry: ${DOCKER_REGISTRY_URL}

imagePullSecrets:
  - name: ${DOCKER_REGISTRY_SECRET}

senzing:
  databaseUrl: "${SENZING_DATABASE_URL}"
  persistentVolumeClaim: senzing-persistent-volume-claim
  subcommand: service

service:
  port: 5000
  nodePort: 31111
  type: NodePort
