apiVersion: v1
kind: PersistentVolume
metadata:
  name: senzing-persistent-volume
finalizers:
- kubernetes.io/pv-protection
spec:
  capacity:
    storage: 20Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: oketi-gluster
