apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: senzing-pvc
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 20Gi
  storageClassName: oketi-gluster
